### ISSUE TITLE
Board bring up checklist

### ISSUE THREAD

**Issue by charlesmacd** [charlesmacd/sbc_pga#2]
- [ ] Validate LEDs
- [X] Validate MC68012RC operation
- [ ] Validate expansion signals (RMC# and A24-A31)
- [ ] Validate AS# selection jumper
